/* tslint:disable */
/* eslint-disable */
/**
 * attendance-management-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * コメントの識別ID
     * @type {number}
     * @memberof Comment
     */
    'id': number;
    /**
     * コメント主のユーザーID
     * @type {string}
     * @memberof Comment
     */
    'userId': string;
    /**
     * コメント本文
     * @type {string}
     * @memberof Comment
     */
    'comment': string;
    /**
     * 投稿日時
     * @type {string}
     * @memberof Comment
     */
    'createdAt': string;
}
/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * デバイスの識別ID
     * @type {number}
     * @memberof Device
     */
    'id': number;
    /**
     * デバイスを所持しているユーザーのID
     * @type {string}
     * @memberof Device
     */
    'userId': string;
    /**
     * デバイスの名前
     * @type {string}
     * @memberof Device
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface DeviceAllOf
 */
export interface DeviceAllOf {
    /**
     * デバイスの識別ID
     * @type {number}
     * @memberof DeviceAllOf
     */
    'id'?: number;
}
/**
 * 
 * @export
 * @interface DeviceDynamicProps
 */
export interface DeviceDynamicProps {
    /**
     * デバイスを所持しているユーザーのID
     * @type {string}
     * @memberof DeviceDynamicProps
     */
    'userId'?: string;
    /**
     * デバイスの名前
     * @type {string}
     * @memberof DeviceDynamicProps
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface InroomAndOutroomUsers
 */
export interface InroomAndOutroomUsers {
    /**
     * 
     * @type {Array<InroomAndOutroomUsersInRoomInner>}
     * @memberof InroomAndOutroomUsers
     */
    'inRoom': Array<InroomAndOutroomUsersInRoomInner>;
    /**
     * 
     * @type {Array<InroomAndOutroomUsersInRoomInnerAllOfUsersInner>}
     * @memberof InroomAndOutroomUsers
     */
    'outRoom': Array<InroomAndOutroomUsersInRoomInnerAllOfUsersInner>;
}
/**
 * 
 * @export
 * @interface InroomAndOutroomUsersInRoomInner
 */
export interface InroomAndOutroomUsersInRoomInner {
    /**
     * 部屋の識別ID
     * @type {number}
     * @memberof InroomAndOutroomUsersInRoomInner
     */
    'id': number;
    /**
     * 部屋の名前
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInner
     */
    'name': string;
    /**
     * 
     * @type {Array<InroomAndOutroomUsersInRoomInnerAllOfUsersInner>}
     * @memberof InroomAndOutroomUsersInRoomInner
     */
    'users': Array<InroomAndOutroomUsersInRoomInnerAllOfUsersInner>;
}
/**
 * 
 * @export
 * @interface InroomAndOutroomUsersInRoomInnerAllOf
 */
export interface InroomAndOutroomUsersInRoomInnerAllOf {
    /**
     * 
     * @type {Array<InroomAndOutroomUsersInRoomInnerAllOfUsersInner>}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOf
     */
    'users': Array<InroomAndOutroomUsersInRoomInnerAllOfUsersInner>;
}
/**
 * 
 * @export
 * @interface InroomAndOutroomUsersInRoomInnerAllOfUsersInner
 */
export interface InroomAndOutroomUsersInRoomInnerAllOfUsersInner {
    /**
     * ユーザーの識別ID
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'id': string;
    /**
     * ユーザーの名前
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'name': string;
    /**
     * ユーザーの学年
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'grade': InroomAndOutroomUsersInRoomInnerAllOfUsersInnerGradeEnum;
    /**
     * ユーザーのプロフィール画像
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'iconUrl': string;
    /**
     * 
     * @type {Comment}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'comment'?: Comment;
    /**
     * 
     * @type {Nickname}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'nickname'?: Nickname;
    /**
     * 
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInner
     */
    'lastConnectedAt'?: string;
}

export const InroomAndOutroomUsersInRoomInnerAllOfUsersInnerGradeEnum = {
    B1: 'B1',
    B2: 'B2',
    B3: 'B3',
    B4: 'B4',
    M1: 'M1',
    M2: 'M2',
    D1: 'D1',
    D2: 'D2',
    D3: 'D3'
} as const;

export type InroomAndOutroomUsersInRoomInnerAllOfUsersInnerGradeEnum = typeof InroomAndOutroomUsersInRoomInnerAllOfUsersInnerGradeEnum[keyof typeof InroomAndOutroomUsersInRoomInnerAllOfUsersInnerGradeEnum];

/**
 * 
 * @export
 * @interface InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf
 */
export interface InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf {
    /**
     * 
     * @type {Comment}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf
     */
    'comment'?: Comment;
}
/**
 * 
 * @export
 * @interface InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf1
 */
export interface InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf1 {
    /**
     * 
     * @type {Nickname}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf1
     */
    'nickname'?: Nickname;
}
/**
 * 
 * @export
 * @interface InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf2
 */
export interface InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf2 {
    /**
     * 
     * @type {string}
     * @memberof InroomAndOutroomUsersInRoomInnerAllOfUsersInnerAllOf2
     */
    'lastConnectedAt'?: string;
}
/**
 * 
 * @export
 * @interface MacAddress
 */
export interface MacAddress {
    /**
     * MacAddressの識別ID
     * @type {number}
     * @memberof MacAddress
     */
    'id': number;
    /**
     * 最終接続日時
     * @type {string}
     * @memberof MacAddress
     */
    'lastConnectedAt': string;
    /**
     * デバイスのmacaddress
     * @type {string}
     * @memberof MacAddress
     */
    'address': string;
    /**
     * 接続先のネットワークのID
     * @type {number}
     * @memberof MacAddress
     */
    'networkId': number;
    /**
     * デバイスの識別ID
     * @type {number}
     * @memberof MacAddress
     */
    'deviceId': number;
}
/**
 * 
 * @export
 * @interface MacAddressAllOf
 */
export interface MacAddressAllOf {
    /**
     * MacAddressの識別ID
     * @type {number}
     * @memberof MacAddressAllOf
     */
    'id'?: number;
    /**
     * 最終接続日時
     * @type {string}
     * @memberof MacAddressAllOf
     */
    'lastConnectedAt'?: string;
}
/**
 * 
 * @export
 * @interface MacAddressDynamicProps
 */
export interface MacAddressDynamicProps {
    /**
     * デバイスのmacaddress
     * @type {string}
     * @memberof MacAddressDynamicProps
     */
    'address'?: string;
    /**
     * 接続先のネットワークのID
     * @type {number}
     * @memberof MacAddressDynamicProps
     */
    'networkId'?: number;
    /**
     * デバイスの識別ID
     * @type {number}
     * @memberof MacAddressDynamicProps
     */
    'deviceId'?: number;
}
/**
 * 
 * @export
 * @interface Network
 */
export interface Network {
    /**
     * ネットワークの識別ID
     * @type {number}
     * @memberof Network
     */
    'id': number;
    /**
     * ネットワークの置かれている部屋のID
     * @type {number}
     * @memberof Network
     */
    'roomId': number;
    /**
     * ネットワークの名前
     * @type {string}
     * @memberof Network
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface Nickname
 */
export interface Nickname {
    /**
     * ニックネームの識別ID
     * @type {number}
     * @memberof Nickname
     */
    'id': number;
    /**
     * ニックネームを付けたユーザーのID
     * @type {string}
     * @memberof Nickname
     */
    'fromId': string;
    /**
     * ニックネームの付けられたユーザーのID
     * @type {string}
     * @memberof Nickname
     */
    'toId': string;
    /**
     * ニックネーム
     * @type {string}
     * @memberof Nickname
     */
    'nickname': string;
}
/**
 * 
 * @export
 * @interface Room
 */
export interface Room {
    /**
     * 部屋の識別ID
     * @type {number}
     * @memberof Room
     */
    'id': number;
    /**
     * 部屋の名前
     * @type {string}
     * @memberof Room
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface UpdateLastConnectedAtRequest
 */
export interface UpdateLastConnectedAtRequest {
    /**
     * 部屋の識別ID
     * @type {number}
     * @memberof UpdateLastConnectedAtRequest
     */
    'roomId'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateLastConnectedAtRequest
     */
    'macAddresses'?: Array<string>;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * ユーザーの識別ID
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * ユーザーの名前
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * ユーザーの学年
     * @type {string}
     * @memberof User
     */
    'grade': UserGradeEnum;
    /**
     * ユーザーのプロフィール画像
     * @type {string}
     * @memberof User
     */
    'iconUrl': string;
}

export const UserGradeEnum = {
    B1: 'B1',
    B2: 'B2',
    B3: 'B3',
    B4: 'B4',
    M1: 'M1',
    M2: 'M2',
    D1: 'D1',
    D2: 'D2',
    D3: 'D3'
} as const;

export type UserGradeEnum = typeof UserGradeEnum[keyof typeof UserGradeEnum];

/**
 * 
 * @export
 * @interface UserAllOf
 */
export interface UserAllOf {
    /**
     * ユーザーの識別ID
     * @type {string}
     * @memberof UserAllOf
     */
    'id'?: string;
}
/**
 * 
 * @export
 * @interface UserDevice
 */
export interface UserDevice {
    /**
     * 
     * @type {Array<UserDeviceRoomsInner>}
     * @memberof UserDevice
     */
    'rooms': Array<UserDeviceRoomsInner>;
}
/**
 * 
 * @export
 * @interface UserDeviceRoomsInner
 */
export interface UserDeviceRoomsInner {
    /**
     * 部屋の識別ID
     * @type {number}
     * @memberof UserDeviceRoomsInner
     */
    'id': number;
    /**
     * 部屋の名前
     * @type {string}
     * @memberof UserDeviceRoomsInner
     */
    'name': string;
    /**
     * 
     * @type {Array<UserDeviceRoomsInnerAllOfDevicesInner>}
     * @memberof UserDeviceRoomsInner
     */
    'devices': Array<UserDeviceRoomsInnerAllOfDevicesInner>;
}
/**
 * 
 * @export
 * @interface UserDeviceRoomsInnerAllOf
 */
export interface UserDeviceRoomsInnerAllOf {
    /**
     * 
     * @type {Array<UserDeviceRoomsInnerAllOfDevicesInner>}
     * @memberof UserDeviceRoomsInnerAllOf
     */
    'devices': Array<UserDeviceRoomsInnerAllOfDevicesInner>;
}
/**
 * 
 * @export
 * @interface UserDeviceRoomsInnerAllOfDevicesInner
 */
export interface UserDeviceRoomsInnerAllOfDevicesInner {
    /**
     * デバイスの識別ID
     * @type {number}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInner
     */
    'id': number;
    /**
     * デバイスを所持しているユーザーのID
     * @type {string}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInner
     */
    'userId': string;
    /**
     * デバイスの名前
     * @type {string}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInner
     */
    'name': string;
    /**
     * 
     * @type {Array<UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner>}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInner
     */
    'addresses': Array<UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner>;
}
/**
 * 
 * @export
 * @interface UserDeviceRoomsInnerAllOfDevicesInnerAllOf
 */
export interface UserDeviceRoomsInnerAllOfDevicesInnerAllOf {
    /**
     * 
     * @type {Array<UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner>}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInnerAllOf
     */
    'addresses': Array<UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner>;
}
/**
 * 
 * @export
 * @interface UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner
 */
export interface UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner {
    /**
     * 
     * @type {Network}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner
     */
    'network': Network;
    /**
     * 
     * @type {MacAddress}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInner
     */
    'macAddress'?: MacAddress;
}
/**
 * 
 * @export
 * @interface UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInnerAllOf
 */
export interface UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInnerAllOf {
    /**
     * 
     * @type {Network}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInnerAllOf
     */
    'network': Network;
    /**
     * 
     * @type {MacAddress}
     * @memberof UserDeviceRoomsInnerAllOfDevicesInnerAllOfAddressesInnerAllOf
     */
    'macAddress'?: MacAddress;
}
/**
 * 
 * @export
 * @interface UserDynamicProps
 */
export interface UserDynamicProps {
    /**
     * ユーザーの名前
     * @type {string}
     * @memberof UserDynamicProps
     */
    'name'?: string;
    /**
     * ユーザーの学年
     * @type {string}
     * @memberof UserDynamicProps
     */
    'grade'?: UserDynamicPropsGradeEnum;
    /**
     * ユーザーのプロフィール画像
     * @type {string}
     * @memberof UserDynamicProps
     */
    'iconUrl'?: string;
}

export const UserDynamicPropsGradeEnum = {
    B1: 'B1',
    B2: 'B2',
    B3: 'B3',
    B4: 'B4',
    M1: 'M1',
    M2: 'M2',
    D1: 'D1',
    D2: 'D2',
    D3: 'D3'
} as const;

export type UserDynamicPropsGradeEnum = typeof UserDynamicPropsGradeEnum[keyof typeof UserDynamicPropsGradeEnum];


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary MACアドレスの最終接続日時を更新する
         * @param {UpdateLastConnectedAtRequest} [updateLastConnectedAtRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLastConnectedAt: async (updateLastConnectedAtRequest?: UpdateLastConnectedAtRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/update_last_connected_at`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateLastConnectedAtRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary MACアドレスの最終接続日時を更新する
         * @param {UpdateLastConnectedAtRequest} [updateLastConnectedAtRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLastConnectedAt(updateLastConnectedAtRequest?: UpdateLastConnectedAtRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLastConnectedAt(updateLastConnectedAtRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary MACアドレスの最終接続日時を更新する
         * @param {UpdateLastConnectedAtRequest} [updateLastConnectedAtRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLastConnectedAt(updateLastConnectedAtRequest?: UpdateLastConnectedAtRequest, options?: any): AxiosPromise<void> {
            return localVarFp.updateLastConnectedAt(updateLastConnectedAtRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary MACアドレスの最終接続日時を更新する
     * @param {UpdateLastConnectedAtRequest} [updateLastConnectedAtRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateLastConnectedAt(updateLastConnectedAtRequest?: UpdateLastConnectedAtRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateLastConnectedAt(updateLastConnectedAtRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RoomsApi - axios parameter creator
 * @export
 */
export const RoomsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ニックネームを新たに設定，または更新
         * @param {Nickname} [nickname] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserNickname: async (nickname?: Nickname, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/rooms/nickname`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nickname, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 部屋情報と各部屋にいるユーザー一覧，ニックネーム，最新のコメントを取得．inRoomには，デバイスの最終接続日時が2分以内のユーザー一覧を部屋ごとに提示(デバイスのlastConnectedAtを参考に計算する)．outRoomには，inRoomではないユーザー一覧を提示する．
         * @summary 各部屋のユーザーとニックネームを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersInRoom: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/rooms/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomsApi - functional programming interface
 * @export
 */
export const RoomsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ニックネームを新たに設定，または更新
         * @param {Nickname} [nickname] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserNickname(nickname?: Nickname, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserNickname(nickname, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 部屋情報と各部屋にいるユーザー一覧，ニックネーム，最新のコメントを取得．inRoomには，デバイスの最終接続日時が2分以内のユーザー一覧を部屋ごとに提示(デバイスのlastConnectedAtを参考に計算する)．outRoomには，inRoomではないユーザー一覧を提示する．
         * @summary 各部屋のユーザーとニックネームを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsersInRoom(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InroomAndOutroomUsers>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsersInRoom(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RoomsApi - factory interface
 * @export
 */
export const RoomsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomsApiFp(configuration)
    return {
        /**
         * 
         * @summary ニックネームを新たに設定，または更新
         * @param {Nickname} [nickname] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserNickname(nickname?: Nickname, options?: any): AxiosPromise<void> {
            return localVarFp.createUserNickname(nickname, options).then((request) => request(axios, basePath));
        },
        /**
         * 部屋情報と各部屋にいるユーザー一覧，ニックネーム，最新のコメントを取得．inRoomには，デバイスの最終接続日時が2分以内のユーザー一覧を部屋ごとに提示(デバイスのlastConnectedAtを参考に計算する)．outRoomには，inRoomではないユーザー一覧を提示する．
         * @summary 各部屋のユーザーとニックネームを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersInRoom(options?: any): AxiosPromise<InroomAndOutroomUsers> {
            return localVarFp.getUsersInRoom(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomsApi - object-oriented interface
 * @export
 * @class RoomsApi
 * @extends {BaseAPI}
 */
export class RoomsApi extends BaseAPI {
    /**
     * 
     * @summary ニックネームを新たに設定，または更新
     * @param {Nickname} [nickname] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomsApi
     */
    public createUserNickname(nickname?: Nickname, options?: AxiosRequestConfig) {
        return RoomsApiFp(this.configuration).createUserNickname(nickname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 部屋情報と各部屋にいるユーザー一覧，ニックネーム，最新のコメントを取得．inRoomには，デバイスの最終接続日時が2分以内のユーザー一覧を部屋ごとに提示(デバイスのlastConnectedAtを参考に計算する)．outRoomには，inRoomではないユーザー一覧を提示する．
     * @summary 各部屋のユーザーとニックネームを取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoomsApi
     */
    public getUsersInRoom(options?: AxiosRequestConfig) {
        return RoomsApiFp(this.configuration).getUsersInRoom(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * SettingApi - axios parameter creator
 * @export
 */
export const SettingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 指定したデバイスを削除．この時，デバイスに紐づけられたMACアドレスも全て削除する．
         * @param {number} deviceId デバイスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDevice: async (deviceId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('deleteDevice', 'deviceId', deviceId)
            const localVarPath = `/api/setting/device/{device_id}`
                .replace(`{${"device_id"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したMACアドレス削除
         * @param {number} macAddressId MACアドレスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMacAddress: async (macAddressId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'macAddressId' is not null or undefined
            assertParamExists('deleteMacAddress', 'macAddressId', macAddressId)
            const localVarPath = `/api/setting/mac_address/{mac_address_id}`
                .replace(`{${"mac_address_id"}}`, encodeURIComponent(String(macAddressId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したデバイスの情報を取得
         * @param {number} deviceId デバイスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevice: async (deviceId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('getDevice', 'deviceId', deviceId)
            const localVarPath = `/api/setting/device/{device_id}`
                .replace(`{${"device_id"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 部屋ごとのデバイスリストと，ネットワーク，MACアドレスを返す
         * @summary 指定したユーザーの持つデバイス一覧を取得
         * @param {string} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevices: async (userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getDevices', 'userId', userId)
            const localVarPath = `/api/setting/devices/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したMACアドレスの情報を取得
         * @param {number} macAddressId MACアドレスID
         * @param {MacAddress} [macAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMacAddress: async (macAddressId: number, macAddress?: MacAddress, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'macAddressId' is not null or undefined
            assertParamExists('getMacAddress', 'macAddressId', macAddressId)
            const localVarPath = `/api/setting/mac_address/{mac_address_id}`
                .replace(`{${"mac_address_id"}}`, encodeURIComponent(String(macAddressId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(macAddress, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 登録されているネットワークの一覧を返す
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNetworks: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/setting/networks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したユーザーの情報を取得
         * @param {string} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUser', 'userId', userId)
            const localVarPath = `/api/setting/user/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 新しいデバイスを追加
         * @param {DeviceDynamicProps} [deviceDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postDevice: async (deviceDynamicProps?: DeviceDynamicProps, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/setting/device`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceDynamicProps, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 新しいMACアドレスを追加
         * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postMacAddress: async (macAddressDynamicProps?: MacAddressDynamicProps, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/setting/mac_address`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(macAddressDynamicProps, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したデバイスの情報を変更
         * @param {number} deviceId デバイスID
         * @param {DeviceDynamicProps} [deviceDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putDevice: async (deviceId: number, deviceDynamicProps?: DeviceDynamicProps, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('putDevice', 'deviceId', deviceId)
            const localVarPath = `/api/setting/device/{device_id}`
                .replace(`{${"device_id"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceDynamicProps, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したMACアドレスの情報を変更
         * @param {number} macAddressId MACアドレスID
         * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putMacAddress: async (macAddressId: number, macAddressDynamicProps?: MacAddressDynamicProps, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'macAddressId' is not null or undefined
            assertParamExists('putMacAddress', 'macAddressId', macAddressId)
            const localVarPath = `/api/setting/mac_address/{mac_address_id}`
                .replace(`{${"mac_address_id"}}`, encodeURIComponent(String(macAddressId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(macAddressDynamicProps, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 指定したユーザーの情報を更新
         * @param {string} userId ユーザーID
         * @param {UserDynamicProps} [userDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser: async (userId: string, userDynamicProps?: UserDynamicProps, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updateUser', 'userId', userId)
            const localVarPath = `/api/setting/user/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userDynamicProps, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SettingApi - functional programming interface
 * @export
 */
export const SettingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SettingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 指定したデバイスを削除．この時，デバイスに紐づけられたMACアドレスも全て削除する．
         * @param {number} deviceId デバイスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDevice(deviceId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDevice(deviceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したMACアドレス削除
         * @param {number} macAddressId MACアドレスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMacAddress(macAddressId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMacAddress(macAddressId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したデバイスの情報を取得
         * @param {number} deviceId デバイスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevice(deviceId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDevice(deviceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 部屋ごとのデバイスリストと，ネットワーク，MACアドレスを返す
         * @summary 指定したユーザーの持つデバイス一覧を取得
         * @param {string} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevices(userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDevice>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDevices(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したMACアドレスの情報を取得
         * @param {number} macAddressId MACアドレスID
         * @param {MacAddress} [macAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMacAddress(macAddressId: number, macAddress?: MacAddress, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMacAddress(macAddressId, macAddress, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 登録されているネットワークの一覧を返す
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNetworks(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Network>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNetworks(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したユーザーの情報を取得
         * @param {string} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 新しいデバイスを追加
         * @param {DeviceDynamicProps} [deviceDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postDevice(deviceDynamicProps?: DeviceDynamicProps, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postDevice(deviceDynamicProps, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 新しいMACアドレスを追加
         * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postMacAddress(macAddressDynamicProps?: MacAddressDynamicProps, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MacAddress>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postMacAddress(macAddressDynamicProps, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したデバイスの情報を変更
         * @param {number} deviceId デバイスID
         * @param {DeviceDynamicProps} [deviceDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putDevice(deviceId: number, deviceDynamicProps?: DeviceDynamicProps, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putDevice(deviceId, deviceDynamicProps, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したMACアドレスの情報を変更
         * @param {number} macAddressId MACアドレスID
         * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putMacAddress(macAddressId: number, macAddressDynamicProps?: MacAddressDynamicProps, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putMacAddress(macAddressId, macAddressDynamicProps, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 指定したユーザーの情報を更新
         * @param {string} userId ユーザーID
         * @param {UserDynamicProps} [userDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser(userId: string, userDynamicProps?: UserDynamicProps, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(userId, userDynamicProps, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SettingApi - factory interface
 * @export
 */
export const SettingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SettingApiFp(configuration)
    return {
        /**
         * 
         * @summary 指定したデバイスを削除．この時，デバイスに紐づけられたMACアドレスも全て削除する．
         * @param {number} deviceId デバイスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDevice(deviceId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteDevice(deviceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したMACアドレス削除
         * @param {number} macAddressId MACアドレスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMacAddress(macAddressId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteMacAddress(macAddressId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したデバイスの情報を取得
         * @param {number} deviceId デバイスID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevice(deviceId: number, options?: any): AxiosPromise<Device> {
            return localVarFp.getDevice(deviceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 部屋ごとのデバイスリストと，ネットワーク，MACアドレスを返す
         * @summary 指定したユーザーの持つデバイス一覧を取得
         * @param {string} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevices(userId: string, options?: any): AxiosPromise<UserDevice> {
            return localVarFp.getDevices(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したMACアドレスの情報を取得
         * @param {number} macAddressId MACアドレスID
         * @param {MacAddress} [macAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMacAddress(macAddressId: number, macAddress?: MacAddress, options?: any): AxiosPromise<void> {
            return localVarFp.getMacAddress(macAddressId, macAddress, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 登録されているネットワークの一覧を返す
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNetworks(options?: any): AxiosPromise<Array<Network>> {
            return localVarFp.getNetworks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したユーザーの情報を取得
         * @param {string} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(userId: string, options?: any): AxiosPromise<User> {
            return localVarFp.getUser(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 新しいデバイスを追加
         * @param {DeviceDynamicProps} [deviceDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postDevice(deviceDynamicProps?: DeviceDynamicProps, options?: any): AxiosPromise<Device> {
            return localVarFp.postDevice(deviceDynamicProps, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 新しいMACアドレスを追加
         * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postMacAddress(macAddressDynamicProps?: MacAddressDynamicProps, options?: any): AxiosPromise<MacAddress> {
            return localVarFp.postMacAddress(macAddressDynamicProps, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したデバイスの情報を変更
         * @param {number} deviceId デバイスID
         * @param {DeviceDynamicProps} [deviceDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putDevice(deviceId: number, deviceDynamicProps?: DeviceDynamicProps, options?: any): AxiosPromise<void> {
            return localVarFp.putDevice(deviceId, deviceDynamicProps, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したMACアドレスの情報を変更
         * @param {number} macAddressId MACアドレスID
         * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putMacAddress(macAddressId: number, macAddressDynamicProps?: MacAddressDynamicProps, options?: any): AxiosPromise<void> {
            return localVarFp.putMacAddress(macAddressId, macAddressDynamicProps, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 指定したユーザーの情報を更新
         * @param {string} userId ユーザーID
         * @param {UserDynamicProps} [userDynamicProps] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser(userId: string, userDynamicProps?: UserDynamicProps, options?: any): AxiosPromise<void> {
            return localVarFp.updateUser(userId, userDynamicProps, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SettingApi - object-oriented interface
 * @export
 * @class SettingApi
 * @extends {BaseAPI}
 */
export class SettingApi extends BaseAPI {
    /**
     * 
     * @summary 指定したデバイスを削除．この時，デバイスに紐づけられたMACアドレスも全て削除する．
     * @param {number} deviceId デバイスID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public deleteDevice(deviceId: number, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).deleteDevice(deviceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したMACアドレス削除
     * @param {number} macAddressId MACアドレスID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public deleteMacAddress(macAddressId: number, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).deleteMacAddress(macAddressId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したデバイスの情報を取得
     * @param {number} deviceId デバイスID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public getDevice(deviceId: number, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).getDevice(deviceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 部屋ごとのデバイスリストと，ネットワーク，MACアドレスを返す
     * @summary 指定したユーザーの持つデバイス一覧を取得
     * @param {string} userId ユーザーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public getDevices(userId: string, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).getDevices(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したMACアドレスの情報を取得
     * @param {number} macAddressId MACアドレスID
     * @param {MacAddress} [macAddress] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public getMacAddress(macAddressId: number, macAddress?: MacAddress, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).getMacAddress(macAddressId, macAddress, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 登録されているネットワークの一覧を返す
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public getNetworks(options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).getNetworks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したユーザーの情報を取得
     * @param {string} userId ユーザーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public getUser(userId: string, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).getUser(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 新しいデバイスを追加
     * @param {DeviceDynamicProps} [deviceDynamicProps] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public postDevice(deviceDynamicProps?: DeviceDynamicProps, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).postDevice(deviceDynamicProps, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 新しいMACアドレスを追加
     * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public postMacAddress(macAddressDynamicProps?: MacAddressDynamicProps, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).postMacAddress(macAddressDynamicProps, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したデバイスの情報を変更
     * @param {number} deviceId デバイスID
     * @param {DeviceDynamicProps} [deviceDynamicProps] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public putDevice(deviceId: number, deviceDynamicProps?: DeviceDynamicProps, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).putDevice(deviceId, deviceDynamicProps, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したMACアドレスの情報を変更
     * @param {number} macAddressId MACアドレスID
     * @param {MacAddressDynamicProps} [macAddressDynamicProps] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public putMacAddress(macAddressId: number, macAddressDynamicProps?: MacAddressDynamicProps, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).putMacAddress(macAddressId, macAddressDynamicProps, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 指定したユーザーの情報を更新
     * @param {string} userId ユーザーID
     * @param {UserDynamicProps} [userDynamicProps] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingApi
     */
    public updateUser(userId: string, userDynamicProps?: UserDynamicProps, options?: AxiosRequestConfig) {
        return SettingApiFp(this.configuration).updateUser(userId, userDynamicProps, options).then((request) => request(this.axios, this.basePath));
    }
}


