openapi: 3.0.0
info:
  title: attendance-management-api
  version: "1.0"
servers:
  - url: "http://localhost:3000"
tags:
  - name: rooms
    description: 在室一覧(/rooms)ページで用いるAPI群
  - name: setting
    description: ユーザー情報設定(/setting)ページで用いるAPI群
paths:
  "/api/rooms/users":
    get:
      tags:
        - rooms
      summary: 各部屋のユーザーとニックネームを取得
      operationId: getUsersInRoom
      description: "部屋情報と各部屋にいるユーザー一覧，ニックネーム，最新のコメントを取得．inRoomには，デバイスの最終接続日時が2分以内のユーザー一覧を部屋ごとに提示(デバイスのlastConnectedAtを参考に計算する)．outRoomには，inRoomではないユーザー一覧を提示する．"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './responses/inroom_and_outroom_users.yaml'
  "/api/rooms/nickname":
    put:
      tags: 
        - rooms
      summary: ニックネームを新たに設定，または更新
      operationId: createUserNickname
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
                $ref: "./components/nickname.yaml"
  "/api/setting/user/{user_id}":
    parameters:
      - $ref: "./parameters/user_id.yaml"
    get:
      summary: 指定したユーザーの情報を取得
      tags:
        - setting
      operationId: getUser
      description: ""
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./components/user.yaml"
    put:
      summary: 指定したユーザーの情報を更新
      tags:
        - setting
      operationId: updateUser
      description: ""
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
                $ref: "./requestBody/user.yaml"
                required:

  "/api/setting/devices/{user_id}":
    parameters:
      - $ref: "./parameters/user_id.yaml"
    get:
      summary: 指定したユーザーの持つデバイス一覧を取得
      tags:
        - setting
      operationId: getDevices
      description: 部屋ごとのデバイスリストと，ネットワーク，MACアドレスを返す
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './responses/user_device.yaml'
  "/api/setting/device/{device_id}":
    parameters:
      - $ref: "./parameters/device_id.yaml"
    put:
      summary: 指定したデバイスの情報を変更
      tags:
        - setting
      operationId: putDevices
      description: ""
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./requestBody/device.yaml"